
CREATE TABLE pollution
(
    id SERIAL PRIMARY KEY,
    dates DATETIME NOT NULL,
    aqi DECIMAL NOT NULL,
    co DECIMAL NOT NULL,
    "no" DECIMAL NOT NULL,
    no2 DECIMAL NOT NULL,
    o3 DECIMAL NOT NULL,
    pm2_5 DECIMAL NOT NULL,
    pm10 DECIMAL NOT NULL,
    so2 DECIMAL NOT NULL
);
